CREATE DATABASE Achados_E_Perdidos;
USE Achados_E_Perdidos;

-- <CRIAÇÃO DE TABELA>

-- Tabela de Itens (O objeto em si)
CREATE TABLE ITEM (
    ID_ITEM INT PRIMARY KEY AUTO_INCREMENT AUTO_INCREMENT,
    NOME_ITEM VARCHAR(100) NOT NULL,
    DESCRICAO TEXT,
    DATA_ACHADO DATE,
    LOCAL_ACHADO VARCHAR(100),
    STATUS_ITEM ENUM('disponivel', 'devolvido') DEFAULT 'disponivel'
);

-- Tabela de quem ENCONTROU o item (Devolutor)
CREATE TABLE DEVOLUTOR (
    CPF_DEVOLUTOR VARCHAR(14) PRIMARY KEY,
    NOME_DEVOLUTOR VARCHAR(100) NOT NULL,
    TELEFONE_DEVOLUTOR VARCHAR(15),
    EMAIL_DEVOLUTOR VARCHAR(100)
);

-- Tabela de quem PERDEU e está procurando (Reclamante)
CREATE TABLE RECLAMANTE (
    CPF_RECLAMANTE VARCHAR(14) PRIMARY KEY,
    NOME_RECLAMANTE VARCHAR(100) NOT NULL,
    TELEFONE_RECLAMANTE VARCHAR(15),
    EMAIL_RECLAMANTE VARCHAR(100)
);

-- Tabela de Cruzamento (A entrega do item)
CREATE TABLE ENTREGAS (
    ID_ENTREGA INT PRIMARY KEY AUTO_INCREMENT,
    ID_ITEM INT,
    CPF_RECLAMANTE VARCHAR(14),
    CPF_DEVOLUTOR VARCHAR(14),
    DATA_ENTREGA DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (ID_ITEM) REFERENCES ITEM(ID_ITEM),
    FOREIGN KEY (CPF_RECLAMANTE) REFERENCES RECLAMANTE(CPF_RECLAMANTE),
    FOREIGN KEY (CPF_DEVOLUTOR) REFERENCES DEVOLUTOR(CPF_DEVOLUTOR)
);

-- <FECHAMENTO DE CRIAÇÃO DE TABELAS>



-- <DROP TALES>

DROP TABLE ITEM;
DROP TABLE DEVOLUTOR;
DROP TABLE RECLAMANTE;
DROP TABLE ENTREGAS;

-- <FECHAMENTO DROP TABLES>



-- <SIMULAÇÃO DE INSERTS>

-- Cadastrando o item achado
INSERT INTO ITEM (NOME_ITEM, DATA_ACHADO, LOCAL_ACHADO) 
VALUES ('Livro de História', '2023-10-25', 'Biblioteca Central');

-- Cadastrando quem achou
INSERT INTO DEVOLUTOR (CPF_DEVOLUTOR, NOME_DEVOLUTOR, TELEFONE_DEVOLUTOR) 
VALUES ('123.456.789-00', 'João Silva', '(11) 99999-9999');

-- Registrando a entrega para quem perdeu
INSERT INTO RECLAMANTE (CPF_RECLAMANTE, NOME_RECLAMANTE) 
VALUES ('987.654.321-11', 'Maria Oliveira');

INSERT INTO ENTREGAS (ID_ITEM, CPF_RECLAMANTE, CPF_DEVOLUTOR) 
VALUES (1, '987.654.321-11', '123.456.789-00');

-- <FECHAMENTO DA SIMULAÇÃO DE INSERTS>